config/routes.rb
V1FmiLicenta::Application.routes.draw do
  
  resources :deadlines
  resources :comentariu_temas
  resources :comentariu_fisiers
  resources :comentariu_capitols
  resources :comentariu_licentas
  resources :licenta_salvatas
  resources :licentas
  resources :todos
  resources :fisiers
  resources :capitols
  resources :alegeri_user_temas
  resources :temas
  resources :domenius
  resources :users
  resources :sesiunes

  get "browse_pagini/viewDataBase" => "browse_pagini#viewDataBase", as: "viewDataBase"
  get "browse_pagini/listaFeatures" => "browse_pagini#listaFeatures", as: "listaFeatures"
  get "browse_pagini/neutralPage" => "browse_pagini#neutralPage", as: "neutralPage"
  
  get "admin_pagini/controlPanel" => "admin_pagini#controlPanel", as: "controlPanel"
  get "admin_pagini/userSpecializari" => "admin_pagini#userSpecializari", as: "userSpecializari"
  get "browse_pagini/browseHome" => "browse_pagini#browseHome", as: "browseHome"
  get "browse_pagini/browseHomeArhiva" => "browse_pagini#browseHomeArhiva", as: "browseHomeArhiva"
  get "browse_pagini/alegerileMele" => "browse_pagini#alegerileMele", as: "alegerileMele"
  get "browse_pagini/studentiiMei" => "browse_pagini#studentiiMei", as: "studentiiMei"
  get "browse_pagini/temeleMele" => "browse_pagini#temeleMele", as: "temeleMele"
  get "browse_pagini/arhivaHome" => "browse_pagini#arhivaHome", as: "arhivaHome"
  get "browse_pagini/intreabaPage" => "browse_pagini#intreabaPage", as: "intreaba"
  get "licenta_pagini/licentaHome" => "licenta_pagini#licentaHome", as: "licentaHome"

  get "domenius/new" => "domenius#new", as: "domeniuNew"
  get "temas/new" => "temas#new", as: "temaNew"
  get "fisiers/:id/download" => "fisiers#download", as: "download_fisier"

  match "/acceptaCaLicenta" => "browse_pagini#acceptaCaLicenta", :as => :acceptaCaLicenta , via: [:get, :post] # pt a accepta licenta (partea de browse)
  match "/acceptStudenti" => "browse_pagini#acceptStudenti", :as => :acceptStudenti , via: [:get, :post]
  match "/refuzStudenti" => "browse_pagini#refuzStudenti", :as => :refuzStudenti , via: [:get, :post]
  match "/renunta" => "licenta_pagini#renuntaLaLicenta", :as => :renunta , via: [:get, :post]
  match "/submitLicentaFinala" => "licenta_pagini#submitLicentaFinala", :as => :submitLicentaFinala , via: [:get, :post]
  match "intreaba/send", to: "browse_pagini#sendmail", via: "post"
  match "licentaHome/adauga_comentariu", to: "licenta_pagini#adauga_comentariu", via: "post"
  match "fisiers/adauga_comentariu", to: "fisiers#adauga_comentariu", via: "post"
  match "capitols/adauga_comentariu", to: "capitols#adauga_comentariu", via: "post"
  match "intreaba/adauga_comentariu", to: "browse_pagini#adauga_comentariu", via: "post"

  # omniauth
  get '/auth/:provider/callback', :to => 'user_sessions#create'
  get '/auth/failure', :to => 'user_sessions#failure'
  match '/logout', :to => 'user_sessions#destroy', :as => :logout, via: [:get, :post]

  root to: "browse_pagini#neutralPage"

end

app/models/capitol.rb
class Capitol < ActiveRecord::Base
	belongs_to :licenta
    has_many :comentariu_capitols
    has_many :todos
    has_many :fisiers
    
    validates :nume, presence: true
end

app/controllers/capitols_controller.rb
class CapitolsController < ApplicationController
  before_filter :check_if_owner_or_prof_of_owner, only: :show
  before_filter :check_if_student, only: [:new, :create]
  before_filter :check_if_owner ,only: [:edit, :update, :destroy]

  before_action :set_capitol, only: [:show, :edit, :update, :destroy]

  # GET /capitols
  # GET /capitols.json
  # def index
    # @capitols = Capitol.all
  # end

  # GET /capitols/1
  # GET /capitols/1.json
  def show
    @fisierele = Fisier.where(capitol_id: @capitol.id)
    @todouri = Todo.where(capitol_id: @capitol.id)
    @comentarii = ComentariuCapitol.where(capitol_id: @capitol.id)
    @studentid = Licenta.find(@capitol.licenta_id).user_id
    @student = User.find(@studentid)
    @tema = Tema.find(Licenta.find(@capitol.licenta_id).tema_id)
  end
  
  def adauga_comentariu
    ComentariuCapitol.create(continut: params[:comentariu], user_id: get_current_user.id, capitol_id: params[:capitol])
    redirect_to Capitol.find(params[:capitol])
  end

  # GET /capitols/new
  def new
      @capitol = Capitol.new
      licenta_id = Licenta.where(user_id: get_current_user.id)
      @capitole = Capitol.where(licenta_id: licenta_id)
  end

  # GET /capitols/1/edit
  def edit
  end

  # POST /capitols
  # POST /capitols.json
  def create
    @capitol = Capitol.new(capitol_params)

    if Licenta.find(@capitol.licenta_id).user_id == get_current_user.id
      respond_to do |format|
        if @capitol.save

          # actualizeaza numerele la restul capitolelor de dupa asta nou
          if Capitol.where("numar = ?", "#{@capitol.numar}").count > 1
            @capitole = Capitol.where("numar >= ? and id != ?", "#{@capitol.numar}", "#{@capitol.id}")
            @capitole.each do |cap|
              numar = cap.numar + 1
              cap.update_attributes(numar: numar)
            end
          end

          format.html { redirect_to root_path, notice: 'Capitol was successfully created.' }
          format.json { render action: 'show', status: :created, location: @capitol }
        else
          format.html { render action: 'new' }
          format.json { render json: @capitol.errors, status: :unprocessable_entity }
        end
      end
    else
      redirect_to root_path
    end
  end

  # PATCH/PUT /capitols/1
  # PATCH/PUT /capitols/1.json
  def update
    respond_to do |format|
      if @capitol.update(capitol_params)
        format.html { redirect_to root_path, notice: 'Capitol was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @capitol.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /capitols/1
  # DELETE /capitols/1.json
  def destroy
    capitol_id = @capitol.id
    licenta_id = @capitol.licenta_id
    numar = @capitol.numar
    @capitol.destroy

    # actualizeaza numerele la restul capitolelor de dupa asta distrus
    @capitole = Capitol.where("licenta_id = ? and numar > ?", "#{licenta_id}", "#{numar}")
    if @capitole.count > 0
      @capitole.each do |cap|
        cap.update_attributes(numar: cap.numar-1)
      end
    end

    # sterge si todo-urile capitolului aluia din baza de date
    Todo.where(capitol_id: capitol_id).delete_all

    respond_to do |format|
      format.html { redirect_to root_path }
      format.json { head :no_content }
    end
  end

  protected

  def check_if_owner_or_prof_of_owner
    @capitol = Capitol.find(params[:id])
    if get_current_user
      licenta_capitol_id = @capitol.licenta_id
      # licenta studentului logat trebuie sa fie aceeasi cu licenta capitolului pe care il acceseaza 
      if get_current_user.rol == "Student"
        licenta = Licenta.where(user_id: get_current_user.id, sesiune_id: get_current_sesiune.id).first
        if licenta
          if licenta.id != licenta_capitol_id
            redirect_to root_path
          end
        else
          redirect_to root_path
        end
      # id-ul profului logat trebuie sa fie acelasi cu id-ul posesorului domeniului temei din licenta de care apartine capitolul :))
      elsif get_current_user.rol == "Profesor"
        tema_id = Licenta.find(licenta_capitol_id).tema_id
        domeniu_id = Tema.find(tema_id).domeniu_id
        prof_id = Domeniu.find(domeniu_id).user_id
        if prof_id != get_current_user.id
          redirect_to root_path
        end
      else
        redirect_to root_path
      end # end of if rol
    else
      redirect_to root_path
    end # end of if current user
  end

  def check_if_student
    if get_current_user
      if get_current_user.rol != "Student"
        redirect_to root_path
      end
    end
  end

  def check_if_owner
    @capitol = Capitol.find(params[:id])
    if get_current_user
      licenta_capitol_id = @capitol.licenta_id
      # licenta studentului logat trebuie sa fie aceeasi cu licenta capitolului pe care il acceseaza 
      if get_current_user.rol == "Student"
        licenta = Licenta.where(user_id: get_current_user.id, sesiune_id: get_current_sesiune.id).first
        if licenta
          if licenta.id != licenta_capitol_id
            redirect_to root_path
          end
        else
          redirect_to root_path
        end
      else
        redirect_to root_path
      end # end of if rol
    else
      redirect_to root_path
    end # end of if current user
  end



  private
    # Use callbacks to share common setup or constraints between actions.
    def set_capitol
      @capitol = Capitol.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def capitol_params
        params.require(:capitol).permit(:licenta_id, :nume, :numar)
    end
end

app/helpers/capitols_helper.rb
module CapitolsHelper
end

app/views/capitols/_form.html.erb
<%= form_for(@capitol) do |f| %>
  
  <!-- afisare erori -->
  <% if @capitol.errors.any? %>
    <div id="error_explanation">
      <ul>
      <% @capitol.errors.full_messages.each do |msg| %>
        <li style="color:red"><%= msg %></li>
      <% end %>
      </ul>
    </div>
    <hr>
  <% end %>


  <% if @capitol.new_record? == true %> <!-- asa se verifica dc e new sau edit :P --> 
    <%= f.hidden_field :numar, :value => @capitole.count+1 %>
  <% end %>

  <% if params[:licenta] %>
      <%= f.hidden_field :licenta_id, :value => params[:licenta] %>
  <% end %>

  <div class="field">
    <%= f.label :nume %><br>
    <%= f.text_field :nume, class:"col-sm-10" %>
  </div>
  
  <br/><br/>
  
  <div class="actions">
    <%= f.submit 'Submit', :class => 'btn btn-primary' %>
  </div>

<% end %>

app/views/capitols/edit.html.erb
<h1>Modifică apitol</h1>
<br/>

<%= render 'form' %>

<%= link_to 'Înapoi', root_path %>

app/views/capitols/new.html.erb
<h1>Capitol nou</h1>
<br/>

<%= render 'form' %>

<%= link_to 'Înapoi', root_path %>

app/views/capitols/show.html.erb
<% if get_current_user.rol == "Profesor"%>
	<%= @student.nume + " " + @student.prenume + " - " + @student.grupa.to_s %>
	<br/>
	<%= @tema.nume %>
	<ol class="breadcrumb">
    	<li><a href="/licenta_pagini/licentaHome?student_id=<%= @studentid%>">Licenta Home</a></li>
    	<li class="active"><%= "Cap" + @capitol.numar.to_s + ". " + @capitol.nume%></li>
	</ol>
<% end %>


<h1>
	<%= "Cap " + @capitol.numar.to_s + ". " + @capitol.nume %>
	<% if get_current_user.rol == "Student" %>
	<%= link_to "", edit_capitol_path(@capitol), class:"glyphicon glyphicon-pencil", :style => 'font-size:14px; color:darkblue; position:relative; left:10px'%>
	<%= link_to "", @capitol, class:"glyphicon glyphicon-trash", method: :delete, data: { confirm: 'Are you sure?' }, :style => 'color:red; font-size:13px; position:relative; left:15px' %>
	<% end %>
</h1>

<!-- notificari -->
<!-- < if flash[:notice] %> -->
   <!-- <hr> -->
   <!-- <div id="notice"><= flash[:notice] %></div> -->
   <!-- <hr> -->
<!-- < end %> -->

<div class="container">
	<div class="row row-offcanvas-right">
		<div class="col-sm-8">

			<br/>

			<!-- afisez todo-urile sale -->
			<% if @todouri.count == 0 %>
				<ul class="list-group">
					<h4 class="list-group-item">ToDos</h4>
					<%if get_current_user.rol == "Student" %>
						<li class="list-group-item"><%= link_to "+ Adaugă ToDo", new_todo_path(:capitol_id => @capitol.id) %></li>
					<% elsif get_current_user.rol == "Profesor" %>
						<li class="list-group-item"><em>Nu sunt todo-uri.</em></li>
					<% end %>
				</ul>
			<% else %>
				<ul class="list-group">
					<h4 class="list-group-item">ToDos</h4>
					<% @todouri.each do |todo| %>
						<% if todo.este_gata == true %>
						<li class="list-group-item list-group-item-success"><%= todo.continut %></li>
						<% elsif todo.este_gata == false %>
						<li class="list-group-item list-group-item-danger"><%= todo.continut %></li>
						<% end %>
					<% end %>
					<%if get_current_user.rol == "Student" %>
						<li class="list-group-item"><%= link_to "+ Adaugă ToDo", new_todo_path(:capitol_id => @capitol.id) %></li>
					<% end %>
				</ul>
			<% end %>

			<!-- afisez fisierele sale -->
			<% if @fisierele.count == 0 %>
				<ul class="list-group">
					<h4 class="list-group-item">Fișiere</h4>
					<%if (@capitol.nume == "Bibliografie" and get_current_user.rol == "Profesor") or get_current_user.rol == "Student" %>
						<li class="list-group-item"><%= link_to "+ Adaugă fișier", new_fisier_path(:capitol_id => @capitol.id) %></li>
					<% elsif get_current_user.rol == "Profesor" and  @capitol.nume != "Bibliografie" %>
						<li class="list-group-item"><em>Nu sunt fișiere.</em></li>
					<% end %>
				</ul>
			<% else %>
				<ul class="list-group">
					<h4 class="list-group-item">Fișiere</h4>
					<% @fisierele.each do |fis| %>
					<!-- as avea nevoie de user_id pt fiecare fisier ca sa stiu cine l-a incarcat - sau de un bool dc e incarcat de prof sau de student ca sa pun culorile sau sa le grupez -->
						<li class="list-group-item list-group-item-info">
							<%= link_to "", download_fisier_path(fis), class: "glyphicon glyphicon-download-alt"%>
							<%= link_to fis.name, fis%>
							(urcat de <%= User.find(fis.user_id).prenume + " " + User.find(fis.user_id).nume %> acum 2 zile)
						</li>
					<% end %>
					<%if (@capitol.nume == "Bibliografie" and get_current_user.rol == "Profesor") or get_current_user.rol == "Student" %>
						<li class="list-group-item"><%= link_to "+ Adaugă fișier", new_fisier_path(:capitol_id => @capitol.id) %></li>
					<% end %>
				</ul>
			<% end %>
		</div>

		<!-- comentariile -->
		<div class="col-sm-3 sidebar-offcanvas" style="overflow:auto; height:550px; position:relative; top:10px">
			<br/>
			<%if @comentarii.count == 0%>
				<em>Nu sunt comentarii.</em>
				<br/><br/>
			<%else%>
				<%@comentarii.each do |comentariu|%>
					<% if User.find(comentariu.user_id).rol == "Profesor" %>
						<div class="panel panel-default">
					  		<div class="panel-heading">
					    		<b><%= User.find(comentariu.user_id).nume + " " + User.find(comentariu.user_id).prenume%> : </b><br/> 
								<em><%= comentariu.created_at.strftime("%d %b. %Y,  %H:%M") %></em>
					  		</div>
					  		<div class="panel-body">
					    		<%= comentariu.continut %>
					  		</div>
						</div>
					<% else %>
						<div class="panel panel-info">
					  		<div class="panel-heading">
					    		<b><%= User.find(comentariu.user_id).nume + " " + User.find(comentariu.user_id).prenume%> : </b><br/> 
								<em><%= comentariu.created_at.strftime("%d %b. %Y,  %H:%M") %></em>
					  		</div>
					  		<div class="panel-body">
					    		<%= comentariu.continut %>
					  		</div>
						</div>
					<% end %>
				<%end%>
			<%end%>
				
			<%= form_tag(capitols_adauga_comentariu_path(:student_id => @student_id), method: "post") do%>
				<%= hidden_field_tag(:capitol, @capitol.id , class: "form-control") %>
				<div class="field">
					<%= text_area_tag(:comentariu, nil , :required => true, class: "form-control",rows:5, placeholder: "Scrie comentariu") %>
				</div>
				<br/>
				<%= submit_tag "Adaugă comentariu", class: "btn btn-primary" %>
			<%end%>
			
		</div>

	</div>
</div>