config/routes.rb
V1FmiLicenta::Application.routes.draw do
  
  resources :deadlines
  resources :comentariu_temas
  resources :comentariu_fisiers
  resources :comentariu_capitols
  resources :comentariu_licentas
  resources :licenta_salvatas
  resources :licentas
  resources :todos
  resources :fisiers
  resources :capitols
  resources :alegeri_user_temas
  resources :temas
  resources :domenius
  resources :users
  resources :sesiunes

  get "browse_pagini/viewDataBase" => "browse_pagini#viewDataBase", as: "viewDataBase"
  get "browse_pagini/listaFeatures" => "browse_pagini#listaFeatures", as: "listaFeatures"
  get "browse_pagini/neutralPage" => "browse_pagini#neutralPage", as: "neutralPage"
  
  get "admin_pagini/controlPanel" => "admin_pagini#controlPanel", as: "controlPanel"
  get "admin_pagini/userSpecializari" => "admin_pagini#userSpecializari", as: "userSpecializari"
  get "browse_pagini/browseHome" => "browse_pagini#browseHome", as: "browseHome"
  get "browse_pagini/browseHomeArhiva" => "browse_pagini#browseHomeArhiva", as: "browseHomeArhiva"
  get "browse_pagini/alegerileMele" => "browse_pagini#alegerileMele", as: "alegerileMele"
  get "browse_pagini/studentiiMei" => "browse_pagini#studentiiMei", as: "studentiiMei"
  get "browse_pagini/temeleMele" => "browse_pagini#temeleMele", as: "temeleMele"
  get "browse_pagini/arhivaHome" => "browse_pagini#arhivaHome", as: "arhivaHome"
  get "browse_pagini/intreabaPage" => "browse_pagini#intreabaPage", as: "intreaba"
  get "licenta_pagini/licentaHome" => "licenta_pagini#licentaHome", as: "licentaHome"

  get "domenius/new" => "domenius#new", as: "domeniuNew"
  get "temas/new" => "temas#new", as: "temaNew"
  get "fisiers/:id/download" => "fisiers#download", as: "download_fisier"

  match "/acceptaCaLicenta" => "browse_pagini#acceptaCaLicenta", :as => :acceptaCaLicenta , via: [:get, :post] # pt a accepta licenta (partea de browse)
  match "/acceptStudenti" => "browse_pagini#acceptStudenti", :as => :acceptStudenti , via: [:get, :post]
  match "/refuzStudenti" => "browse_pagini#refuzStudenti", :as => :refuzStudenti , via: [:get, :post]
  match "/renunta" => "licenta_pagini#renuntaLaLicenta", :as => :renunta , via: [:get, :post]
  match "/submitLicentaFinala" => "licenta_pagini#submitLicentaFinala", :as => :submitLicentaFinala , via: [:get, :post]
  match "intreaba/send", to: "browse_pagini#sendmail", via: "post"
  match "licentaHome/adauga_comentariu", to: "licenta_pagini#adauga_comentariu", via: "post"
  match "fisiers/adauga_comentariu", to: "fisiers#adauga_comentariu", via: "post"
  match "capitols/adauga_comentariu", to: "capitols#adauga_comentariu", via: "post"
  match "intreaba/adauga_comentariu", to: "browse_pagini#adauga_comentariu", via: "post"

  # omniauth
  get '/auth/:provider/callback', :to => 'user_sessions#create'
  get '/auth/failure', :to => 'user_sessions#failure'
  match '/logout', :to => 'user_sessions#destroy', :as => :logout, via: [:get, :post]

  root to: "browse_pagini#neutralPage"

end

app/controllers/browse_pagini_controller.rb
class BrowsePaginiController < ApplicationController
  
  before_filter :login_required, except: :neutralPage#, :temeleMele, :studentiiMei, :alegerileMele]
  before_filter :checkIfProf, only: [:temeleMele, :studentiiMei]
  before_filter :checkIfStudent, only: :alegerileMele

  def neutralPage
    if get_current_user
      redirect_to browseHome_path
    end
  end


  def browseHome

    if get_current_user.rol == "Administrator"
      redirect_to controlPanel_path
    else

      # @current_sesiune = Sesiune.where("data_end is null").first
      # if @current_sesiune == nil
      #   @current_sesiune = Sesiune.where("data_end is not null").last
      # end

      # dc studentul are deja licenta, nu mai are ce cauta pe pg de browse - este dus direct la licenta sa
      if get_current_user
        my_licentas = Licenta.where(user_id: get_current_user.id, sesiune_id: get_current_sesiune.id)
        if my_licentas
          my_licentas.each do |lic|
            if lic.renuntat != true
              redirect_to licentaHome_path
            end
          end  
        end
      end

      # @url_s = "http://fmi-api.herokuapp.com/students/" + session[:user_id]['uid'] + "?oauth_token=" + session[:user_id]['credentials']['token']
      # resp_s = Net::HTTP.get_response(URI.parse(@url_s))
      # @info_curent_s = JSON.parse(resp_s.body)

      # @url_t = "http://fmi-api.herokuapp.com/teachers/" + session[:user_id]['uid'] + "?oauth_token=" + session[:user_id]['credentials']['token']
      # resp_t = Net::HTTP.get_response(URI.parse(@url_t))
      # @info_curent_t = JSON.parse(resp_t.body)
        
      # @url = "http://fmi-api.herokuapp.com/teachers/13?oauth_token=" + session[:user_id]['credentials']['token']
      # resp = Net::HTTP.get_response(URI.parse(@url))
      # @info_curent = JSON.parse(resp.body)

      # cauta cuvintele din search in campurile temelor: nume si descriere
      if params[:search] and params[:search] != ""
        # sparg in cuv dupa virgule
        cuvinte = params[:search].split(/,/)
        @results = Tema.all
        # dc e student, ma uit doar in temele profilor de aceeasi specializare sau ambele specializari
        if get_current_user.rol == "Student"
          @results = @results.where(este_libera: true).where("user_id IN (SELECT id FROM users WHERE specializare LIKE 'Ambele' OR specializare LIKE ?)", "#{get_current_user.specializare}")
        end
        # iau fiecare cuvand din cuvinte si il bag pe rand in query
        cuvinte.each do |cuv|
          @results = @results.where("lower(temas.descriere) LIKE lower(?) or lower(temas.nume) LIKE lower(?)","%#{cuv}%","%#{cuv}%")
        end
        # http://api.rubyonrails.org/classes/ActiveRecord/QueryMethods.html#method-i-from
      end
        
      # profii care sunt eligibili pt licenta (si au aceeasi specializare ca studentul logat)
      if get_current_user and get_current_user.rol == "Student"
        @useri_profesori = User.profesori_eligibili.where("specializare LIKE ? OR 'Ambele'", "#{get_current_user.specializare}")
      else
        @useri_profesori = User.profesori_eligibili
      end

    end # end of if admin
        
  end # end of browseHomec


  def browseHomeArhiva
    @selected_sesiune = Sesiune.find(params[:sesiune_id])
    # @current_sesiune = Sesiune.where("data_end is not null").first

    # tabelele care au sesiune_id sunt:
    # alegeri_user_temas - pt a stii ce lucrari s-au luat si de catre care studenti
    # licenta_salvatas
    # temas - pt a fi afisate in arhiva

    # cauta cuvintele din search in teme: nume si descriere
    if params[:search] and params[:search] != ""
      # sparg in cuv dupa virgule
      cuvinte = params[:search].split(/,/)
      # iau fiecare cuvand din cuvinte si il bag pe rand in query
      @results = Tema.all.where(sesiune_id: @selected_sesiune.id)
      # if get_current_user.rol == "Student"
        # @results = @results.where("user_id IN (SELECT id FROM users WHERE specializare LIKE 'Ambele' OR specializare LIKE ?)", "#{get_current_user.specializare}")
      # end
      cuvinte.each do |cuv|
        @results = @results.where("lower(temas.descriere) LIKE lower(?) or lower(temas.nume) LIKE lower(?)","%#{cuv}%","%#{cuv}%")
      end
      # http://api.rubyonrails.org/classes/ActiveRecord/QueryMethods.html#method-i-from
    end
      
    @useri_profesori = User.profesori_eligibili

    # # profii care sunt eligibili pt licenta
    # if get_current_user and get_current_user.rol == "Student"
    #   @useri_profesori = User.profesori_eligibili.where(specializare: get_current_user.specializare)
    # else
    #   @useri_profesori = User.profesori_eligibili
    # end
      
    # # dc studentul are deja licenta, nu mai are ce cauta pe pg de browse - este dus direct la licenta sa
    # if get_current_user
    #     if Licenta.where(user_id: get_current_user.id).first
    #         redirect_to licentaHome_path
    #     end
    # else
    #     # Daca Studentul nu e logat 
    #     redirect_to sessions_new_path    
    # end

  end # end of browseHomeArhiva


  def alegerileMele
    if params[:tema_id]
      if AlegeriUserTema.where(sesiune_id: get_current_sesiune.id).where(tema_id: params[:tema_id]).where(user_id: get_current_user.id).count == 0
        # @current_sesiune = Sesiune.where("data_end is null").first
        # if @current_sesiune == nil
        #   @current_sesiune = Sesiune.where("data_end is not null").last
        # end
        AlegeriUserTema.create(user_id: get_current_user.id, tema_id: params[:tema_id], status_profesor: "Pending", status_student: "Pending", sesiune_id: get_current_sesiune.id)
        flash[:notice] = "Alegere salvata cu succes"
      else
        flash[:notice] = "Alegerea selectata deja exista"
      end
    end

    temeLibereIds = Tema.where(sesiune_id: get_current_sesiune.id, este_libera: true).pluck(:id)
    @alegeri = AlegeriUserTema.where(sesiune_id: get_current_sesiune.id).where(user_id: get_current_user.id).where(tema_id: temeLibereIds)
  
  end # end of alegerileMele


  def temeleMele
    # @current_sesiune = Sesiune.where("data_end is null").first
    # if @current_sesiune == nil
    #   @current_sesiune = Sesiune.where("data_end is not null").last
    # end

    # afiseaza toate domeniile profului curent, in view se afiseaza si toate temele domeniilor astora
    @domenii = Domeniu.where(user_id: get_current_user.id).where(sesiune_id: get_current_sesiune.id)

  end # end of temeleMele


  def studentiiMei
    #toate domeniile din sesiunea curenta ale userului curent logat
    @domenii = Domeniu.where(sesiune_id: get_current_sesiune.id).where(user_id: get_current_user.id)
    
    @temeAleseDeStudenti = 0
    @domenii.each do |dom|
        dom.temas.each do |t|
            @temeAleseDeStudenti = @temeAleseDeStudenti + AlegeriUserTema.where(sesiune_id: get_current_sesiune.id).where(tema_id: t.id).count
        end
    end
    
    @nrStudentiCuLicenta = 0
    @domenii.each do |domeniu|
        domeniu.temas.each do |tema|
            Licenta.where(tema_id: tema.id, sesiune_id: get_current_sesiune.id, renuntat: false).each do |licenta|
                @nrStudentiCuLicenta = @nrStudentiCuLicenta + 1
            end
        end
    end

  end # end of studentiiMei


  def arhivaHome
    @sesiuni = Sesiune.all.order("data_start ASC")
  end


  def intreabaPage
    @comentarii = ComentariuTema.where(tema_id: params[:tema_id])
  end


  def adauga_comentariu
    ComentariuTema.create(continut: params[:comentariu], user_id: get_current_user.id, tema_id: params[:tema_id])
    redirect_to intreaba_path(tema_id: params[:tema_id])
  end


  def acceptaCaLicenta
      # dau mail profesorului ca acest student a acceptat tema sa.
      #UserMailer.notification_email(User.find(get_current_user.id).email,User.find(Domeniu.find(Tema.find(params[:temaaleasa_id]).domeniu_id).user_id).email, "Acceptare licenta", "Studentul cu numele " + User.find(get_current_user.id).nume + " " + User.find(get_current_user.id).prenume + "este acum studentul dumneavoastra pentru licenta" ).deliver
      
      # creez o intrare noua in licenta ca sa stiu ca acest student are aceasta tema la licenta si lucreaza la ea
      # renuntat == nil inseamna ca nu s-a renuntat la ea pana acum
      # renuntat == true inseamna ca a fost luata de cnv si acum e iar libera - a renuntat la ea
      # renuntat == false inseamna ca a fost renuntata si a luat-o inapoi proprietarul
      
      # caut tema asta 
      previousLicenta = Licenta.where(sesiune_id: get_current_sesiune.id).find_by_tema_id(params[:temaaleasa_id]) # nu ai nevoie de first pt ca e find si tema_id in model e sa fie unic
      licenta = previousLicenta

      # dc nu e - o iau eu pt prima data
      if previousLicenta == nil
        licenta = Licenta.create(user_id: get_current_user.id , tema_id: params[:temaaleasa_id], renuntat: false, sesiune_id: get_current_sesiune.id)
        # creez capitolele de inceput 
        Capitol.create(nume: "Introducere", licenta_id: licenta.id, numar: 1)
        Capitol.create(nume: "Concluzii", licenta_id: licenta.id, numar: 2)
        Capitol.create(nume: "Bibliografie", licenta_id: licenta.id, numar: 3)

      # dc e si are renuntat == true - inseamna ca a fost lasata de cineva (eu sau altul)
      elsif previousLicenta and previousLicenta.renuntat == true
        # dc sunt tot eu doar modific renuntat si nu mai creez alte capitole
        if previousLicenta.user_id == get_current_user.id
          previousLicenta.update_attributes(renuntat: false)
        # dc nu sunt eu tre sa sterg toata munca celui dinaintea mea si inregistrarea asta de licenta si sa fac alta
        else
          # sterg comentarii_licenta
          # if ComentariuLicenta.where(licenta_id: licenta.id).count > 0
          ComentariuLicenta.where(licenta_id: licenta.id).delete_all
          # end
          # sterg capitole
          Capitol.where(licenta_id: licenta.id).each do |cap|

app/helpers/browse_pagini_helper.rb
module BrowsePaginiHelper

	def get_current_user
        @current_user = nil
    	if session[:user_id]
    	   @current_user ||= User.find_by_email(session[:user_id]['extra']['email'])
        end
        return @current_user
    end

	def has_domenii
        if Domeniu.where(user_id: current_user.id).count > 0
            return true
        end
        return false
    end

    def get_current_sesiune
        @current_s = Sesiune.where(este_deschisa: true).first
        # if @current_s == nil
          # @current_s = Sesiune.where("data_end is not null").last
        # end
        return @current_s
    end

end

app/views/browse_pagini/arhivaHome.html.erb
<h1>Arhiva Home</h1>

<% if @sesiuni.count == 0 %>

	There are no previous sessions.

<% else %>

	<table class="table table-striped table hover">
	<thead>
		<tr>
		<th class="col-sm-1">Nr.</th>
		<th>Sesiune</th>
		</tr>
	</thead>
	<tbody>
		<% nr = 0 %>
		<% @sesiuni.each do |sesiune| %>
			<% nr = nr + 1 %>
			<tr>

				<td><%= nr %></td>

				<td>
					<% if sesiune.este_deschisa %>
						<%= link_to sesiune.data_start.strftime("%B %Y") + " - " + "Present", root_path %>
					<% else %>
						<%= link_to sesiune.data_start.strftime("%B %Y") + " - " + sesiune.data_end.strftime("%B %Y"), browseHomeArhiva_path(sesiune_id: sesiune.id) %>
					<% end %>
				</td>

			</tr>
		<% end %>
	</tbody>
	</table>

<% end %>

app/views/browse_pagini/browseHomeArhiva.html.erb
<h1>Toate temele din <%= @selected_sesiune.data_start.strftime("%Y") %> - <%= (@selected_sesiune.data_start.strftime("%Y").to_i + 1).to_s %></h1>
<br/><br/>

<!-- < if flash[:notice] && flash[:notice] != "Alegerea selectata deja exista" && flash[:notice] != "Alegere salvata cu succes"%> -->
   <!-- <div id="notice"><= flash[:notice] %></div> -->
   <!-- <hr> -->
<!-- < end %> -->


<!-- search box -->
<%= form_tag({controller: "browse_pagini", action:"browseHomeArhiva" }, method: "get") do %>
    <div class="form-group search-form">
		<%= text_field_tag(:search,nil, class: ' mysearchbox col-md-3 form-control search-input', :placeholder => "e.g.  servlet, java, promovabil") %>
		<%= hidden_field_tag(:sesiune_id, @selected_sesiune.id) %>
    	<%= submit_tag("Caută", class: 'btn btn-primary', style: "position:relative; left:20px") %>
    </div>
<% end %>
<br/>

<!-- temele din sesiunea curenta -->
<% if params[:search] and params[:search] != "" %>
	
	<% if @results.count > 0 %>
		
		<table class="table table-striped table hover">
			<thead>
				<th>Nr.</th>
				<th>Titlu temă</th>
			</thead>
			<tbody>
				<% nr_tema_searc = 0 %>
				<% @results.each do |r| %>
					<% nr_tema_searc = nr_tema_searc + 1 %>
					<tr>
						<td><%= nr_tema_searc %></td>
						<td><%= link_to r.nume, r %></td>
					</tr>
				<% end %>
			</tbody>
		</table>
	
	<% elsif @results.count == 0 %>
		Nicio tema.
	<% end %>

<% else %>

	<% if @useri_profesori.count == 0 %>
		<p> Nu sunt profesori eligibili pentru licență. </p>
	<% end %>

	<div class="css-treeview">
		<ul> <!-- pt profi -->
			<% @useri_profesori.each do |prof| %>
				<li style="padding-bottom:10px; padding-top:10px;"><input type="checkbox" /><label><span style="font-size:22px;font-family:Georgia, serif;color:black"><%= link_to prof.grad + " " + prof.nume + " " + prof.prenume, prof %><span/></label>
					<ul> <!-- pt domenii -->
						
						<% if Domeniu.where(user_id: prof.id).where(sesiune_id: params[:sesiune_id]).count == 0 %>
							Nu sunt domenii.
						<% else %>

							<% Domeniu.where(user_id: prof.id).where(sesiune_id: params[:sesiune_id]).each do |dom| %>
								<li style="padding-top:10px;"><input type="checkbox" /><label style="font-size:18px;font-family:Georgia, serif; color:darkgreen" for="domeniu"><%= link_to dom.nume, dom %></label>
								
									<br/>

									<ul>
										<% if get_current_user.rol == "Student" %>
											<% if Tema.where(domeniu_id: dom.id).where(sesiune_id: params[:sesiune_id]).count == 0 %>
												<li style="padding-top:10px"><em>Nu sunt teme.</em></li>
											<% else %>
												<table class="table table-striped table hover">
													<thead>
														<th></th>
													</thead>
													<tbody>
														<% Tema.where(domeniu_id: dom.id).where(sesiune_id: params[:sesiune_id]).each do |tema| %>
															<tr>
																<td><%= link_to tema.nume, tema_path(tema, sesiune_id: params[:sesiune_id]) %></td>
															</tr>
															<!-- <li style="list-style-type: circle; padding-top:10px"> -->
																<!-- <span style="font-size:18px;font-family:Georgia, serif;color:black"><= link_to tema.nume, tema %></span> -->
															<!-- </li> end de la tema -->
														<% end %>
													</tbody>
												</table>
											<% end %>
										<% else %>
											
											<% if Tema.where(domeniu_id: dom.id).count == 0 %>
												<li style="padding-top:10px"><em>Nu sunt teme.</em></li>
											<% else %>
												<table class="table table-striped table hover">
													<thead>
														<th></th>
													</thead>
													<tbody>
														<% Tema.where(domeniu_id: dom.id).each do |tema| %>
															<tr>
																<td><%= link_to tema.nume, tema %></td>
															</tr>
														<% end %>
													</tbody>
												</table>
											<% end %>

										<% end %>
									</ul>

								</li> <!-- end de la domeniu -->
							<% end %> <!-- end domenii... each -->
						<% end %> <!-- end if domenii.count -->
					</ul>
				</li> <!-- end de la prof -->
				<hr>
			<% end %>
		</ul>
	</div> <!-- end of div css treeview -->
	
	<br/><br/>

<% end %>

app/views/browse_pagini/intreabaPage.html.erb
<% tema = Tema.find(params[:tema_id]) %>
<h1>Discutii "<%= tema.nume %>"</h1>

<!-- comentariile temei -->
<% if @comentarii.count == 0 %>
	
	<em>Nu sunt comentarii.</em>
	<br/><br/>

<% else %>
	
	<% @comentarii.each do |comentariu| %>
		
		<% if User.find(comentariu.user_id).rol == "Profesor" %>
			
			<div class="panel panel-default">
				<div class="panel-heading">
			    	<b><%= User.find(comentariu.user_id).nume + " " + User.find(comentariu.user_id).prenume%> : </b><br/> 
					<em><%= comentariu.created_at.strftime("%d %b. %Y,  %H:%M") %></em>
			  	</div>
			  	<div class="panel-body">
			    	<%= comentariu.continut %>
			  	</div>
			</div>

		<% else %>
			
			<div class="panel panel-info">
			  	<div class="panel-heading">
			    	<b><%= User.find(comentariu.user_id).nume + " " + User.find(comentariu.user_id).prenume%> : </b><br/> 
					<em><%= time_ago_in_words(comentariu.created_at) %> ago (<%= comentariu.created_at.strftime("%d %b. %Y,  %H:%M") %>) </em>
			  	</div>
			  	<div class="panel-body">
			    	<%= comentariu.continut %>
			  	</div>
			</div>
			
		<% end %>
	
	<%end%>

<%end%>
	
<!-- adauga comentariu -->
<%= form_tag(intreaba_adauga_comentariu_path(user_id: get_current_user.id), method: "post") do %>

	<%= hidden_field_tag(:tema_id, params[:tema_id] , class: "form-control") %>
	
	<div class="field">
		<%= text_area_tag(:comentariu, nil , :required => true, class: "form-control",rows:5) %>
	</div>
	
	<br/>

	<%= submit_tag "Adaugă comentariu", class: "btn btn-primary" %>
	
	<br/>
	
	<%= link_to 'Înapoi', tema_path(tema) %>

<%end%>

app/views/browse_pagini/neutralPage.html.erb
<h1>Please Login.</h1>

app/views/browse_pagini/temeleMele.html.erb
<!-- afiseaza mesaje -->
<% if flash[:notice] %> 
<!-- && flash[:notice] != "Alegerea selectata deja exista" && flash[:notice] != "Alegere salvata cu succes"%> -->
	<div id="notice", style="color:green"><%= flash[:notice] %></div>
	<hr>
<% end %>

<!-- deadlines -->
<% deadlineuriPublice = Deadline.where(public_tinta: 'Toti').where("data_start <= ? and data_end >= ?", "#{Date.today}", "#{Date.today}") %>
<% deadlineuriSpecifice = Deadline.where(public_tinta: get_current_user.rol).where("data_start <= ? and data_end >= ?", "#{Date.today}", "#{Date.today}") %>

<!-- deadlines pt toata lumea -->
<% if deadlineuriPublice.count > 0 %>
	Anunturi de interes general
	<br/>
	<ul class="list-group">
		<% deadlineuriPublice.each do |deadline| %>
	  			<li class="list-group-item list-group-item-info"><%= deadline.nume + " - " + deadline.data_end.strftime("%d %B %Y") + " ( " + distance_of_time_in_words(Date.today, deadline.data_end) + " left )" %></li>
		<% end %>
	</ul>
<% end %>

<!-- deadlines pt tipul celui logat -->
<% if deadlineuriSpecifice.count > 0 %>
	<% if get_current_user.rol == "Student" %>
		Anuntutri pentru studenti
		<br/>
	<% elsif get_current_user.rol == "Profesor" %>
		Anuntutri pentru profesori
		<br/>
	<% end %>	
	<ul class="list-group">
		<% deadlineuriSpecifice.each do |deadline| %>
		  		<li class="list-group-item list-group-item-success"><%= deadline.nume + " " + deadline.data_end.strftime("%d %B %Y") + " ( " + distance_of_time_in_words(Date.today, deadline.data_end) + " left )" %></li>
		<% end %>
	</ul>
<% end %>

<br/>


<h1>Temele mele</h1>
<br/><br/>


<!-- temele mele -->
<table class="table table-striped table hover">
	<thead>
	<tr>
		<th></th>
		<th class="col-sm-1"></th>
	</tr>
	</thead>
	<tbody>

		<!-- Domeniile -->
		<% Domeniu.where(user_id: get_current_user.id).where(sesiune_id: get_current_sesiune.id).each do |dom| %>
		
			<tr>
		
				<td><b><%= link_to dom.nume, dom %></b></td>
		
				<td>
					<% if dom.nume != "Propuneri Studenti" %>
						<%= link_to "", edit_domeniu_path(dom), class:"glyphicon glyphicon-pencil", :style => 'font-size:13px; position:relative; left:10px'%>
						<% if Tema.where(domeniu_id: dom.id).count == 0 %>
							<%= link_to "", dom, class:"glyphicon glyphicon-trash", method: :delete, data: { confirm: 'Are you sure?' }, :style => 'color:red; font-size:13px; position:relative; left:15px' %>
						<% end %>
					<% end %>
				</td>
		
			</tr>
		
			<!-- temele unui domeniu -->
			<tr>
				<td>
					<ul class="list-group">
						<% Tema.where(domeniu_id: dom.id).each do |tema| %>
							<li class="list-group-item list-group-item-default"><%= link_to tema.nume, tema %></li>
						<% end %>
						<li class="list-group-item list-group-item-default"><%= link_to "+  Temă", temaNew_path(domeniu_id: dom.id) %></li>
					</ul>
				</td>
				
				<td>
					<ul class="list-group">
						<% Tema.where(domeniu_id: dom.id).each do |tema| %>
							<li class="list-group-item list-group-item-default">
								<%= link_to "", edit_tema_path(tema), class: "glyphicon glyphicon-pencil", style: "font-size:13px; position:relative; left:10px"%>
								<%= link_to "", tema, class: "glyphicon glyphicon-trash", method: :delete, data: { confirm: 'Sigur?' }, :style => 'color:red; font-size:13px; position:relative; left:15px' %>
							</li>
						<% end %>
					</ul>
				</td>
			</tr>

		<% end %><!-- end al lui domenii.each -->

		<!-- butonul de add domeniu de la final -->
		<tr>
			<td><b><%= link_to "+  Domeniu", domeniuNew_path %></b></td>
			<td></td>
		</tr>

	</tbody>
</table>

<br/>

<!-- buton pentru domeniul propuneri studenti -->
<% if get_current_user.rol == "Profesor" %>
	<% if get_current_user.are_domeniu_propuneri_studenti %>
		<%= link_to "Refuza propuneri de la studenti", refuzStudenti_path(refuzStudenti: true), data: {confirm: "Temele propuse de studenti(daca exista deja) vor ramane in domeniul Neclasificat si vor fi disponibile studentilor pentru a si le alege ca lucrari de licenta."}, class: "btn btn-danger", style: "float:right" %>
	<% else %>
		<%= link_to "Permite propuneri de la studenti", acceptStudenti_path(acceptStudenti: true), class: "btn btn-success", style: "float:right" %>
	<% end %>
<% end %>