config/routes.rb
V1FmiLicenta::Application.routes.draw do
  
  resources :deadlines
  resources :comentariu_temas
  resources :comentariu_fisiers
  resources :comentariu_capitols
  resources :comentariu_licentas
  resources :licenta_salvatas
  resources :licentas
  resources :todos
  resources :fisiers
  resources :capitols
  resources :alegeri_user_temas
  resources :temas
  resources :domenius
  resources :users
  resources :sesiunes

  get "browse_pagini/viewDataBase" => "browse_pagini#viewDataBase", as: "viewDataBase"
  get "browse_pagini/listaFeatures" => "browse_pagini#listaFeatures", as: "listaFeatures"
  get "browse_pagini/neutralPage" => "browse_pagini#neutralPage", as: "neutralPage"
  
  get "admin_pagini/controlPanel" => "admin_pagini#controlPanel", as: "controlPanel"
  get "admin_pagini/userSpecializari" => "admin_pagini#userSpecializari", as: "userSpecializari"
  get "browse_pagini/browseHome" => "browse_pagini#browseHome", as: "browseHome"
  get "browse_pagini/browseHomeArhiva" => "browse_pagini#browseHomeArhiva", as: "browseHomeArhiva"
  get "browse_pagini/alegerileMele" => "browse_pagini#alegerileMele", as: "alegerileMele"
  get "browse_pagini/studentiiMei" => "browse_pagini#studentiiMei", as: "studentiiMei"
  get "browse_pagini/temeleMele" => "browse_pagini#temeleMele", as: "temeleMele"
  get "browse_pagini/arhivaHome" => "browse_pagini#arhivaHome", as: "arhivaHome"
  get "browse_pagini/intreabaPage" => "browse_pagini#intreabaPage", as: "intreaba"
  get "licenta_pagini/licentaHome" => "licenta_pagini#licentaHome", as: "licentaHome"

  get "domenius/new" => "domenius#new", as: "domeniuNew"
  get "temas/new" => "temas#new", as: "temaNew"
  get "fisiers/:id/download" => "fisiers#download", as: "download_fisier"

  match "/acceptaCaLicenta" => "browse_pagini#acceptaCaLicenta", :as => :acceptaCaLicenta , via: [:get, :post] # pt a accepta licenta (partea de browse)
  match "/acceptStudenti" => "browse_pagini#acceptStudenti", :as => :acceptStudenti , via: [:get, :post]
  match "/refuzStudenti" => "browse_pagini#refuzStudenti", :as => :refuzStudenti , via: [:get, :post]
  match "/renunta" => "licenta_pagini#renuntaLaLicenta", :as => :renunta , via: [:get, :post]
  match "/submitLicentaFinala" => "licenta_pagini#submitLicentaFinala", :as => :submitLicentaFinala , via: [:get, :post]
  match "intreaba/send", to: "browse_pagini#sendmail", via: "post"
  match "licentaHome/adauga_comentariu", to: "licenta_pagini#adauga_comentariu", via: "post"
  match "fisiers/adauga_comentariu", to: "fisiers#adauga_comentariu", via: "post"
  match "capitols/adauga_comentariu", to: "capitols#adauga_comentariu", via: "post"
  match "intreaba/adauga_comentariu", to: "browse_pagini#adauga_comentariu", via: "post"

  # omniauth
  get '/auth/:provider/callback', :to => 'user_sessions#create'
  get '/auth/failure', :to => 'user_sessions#failure'
  match '/logout', :to => 'user_sessions#destroy', :as => :logout, via: [:get, :post]

  root to: "browse_pagini#neutralPage"

end

app/models/alegeri_user_tema.rb
class AlegeriUserTema < ActiveRecord::Base
	belongs_to :user
    belongs_to :tema
end

app/models/capitol.rb
class Capitol < ActiveRecord::Base
	belongs_to :licenta
    has_many :comentariu_capitols
    has_many :todos
    has_many :fisiers
    
    validates :nume, presence: true
end

app/models/comentariu_fisier.rb
class ComentariuFisier < ActiveRecord::Base
    belongs_to :fisier
end

app/models/comentariu_tema.rb
class ComentariuTema < ActiveRecord::Base
	belongs_to :tema
end

app/models/deadline.rb
class Deadline < ActiveRecord::Base

	validates :nume, presence: true
    validates :descriere, presence: true
	validates :data_start, presence: true
    validates :data_end, presence: true
    validates :public_tinta, presence: true
    validate :data_start_is_before_data_end

    def data_start_is_before_data_end
    	if data_start > data_end
    		errors.add(:data_end, ": Data_end trebuie sa fie dupa data_start.")
    	end
    end

end

app/models/domeniu.rb
class Domeniu < ActiveRecord::Base
    belongs_to :user
    has_many :temas
    
    def self.search(search)
        search_condition = "%" + search + "%"
        find(:all, :conditions => ['nume LIKE ? OR descriere LIKE ?', search_condition, search_condition])
        #SELECT * FROM foo WHERE bar LIKE "%query%" LIMIT 10;
    end

    validates :nume, presence: true
    validates :user_id, presence: true
	validates :sesiune_id, presence: true

end

app/models/fisier.rb
class Fisier < ActiveRecord::Base
    belongs_to :capitol
    has_many :comentariu_fisiers

validates :name, presence: true
validates :capitol_id, presence: true
# validates :path, presence: true


    def self.save(fisier,upload)
        name =  fisier[:name]
        directory = "public/data/"
        # create the file path
        path = File.join(directory, name)
        #fisier.path = path
        fisier.update_attributes(path: "public/data/" + name)
        # write the file
        File.open(path, "wb") { |f| f.write(upload.tempfile.read) }
    end

end

app/models/licenta.rb
class Licenta < ActiveRecord::Base
    has_many :capitols
    has_many :comentariu_licentas
    
    validates :tema_id, uniqueness: true
end

app/models/sesiune.rb
class Sesiune < ActiveRecord::Base
end

app/models/tema.rb
class Tema < ActiveRecord::Base
    belongs_to :domeniu
    
    validates :nume,  presence: true
    validates :domeniu_id,  presence: true
    
end

app/models/todo.rb
class Todo < ActiveRecord::Base
    belongs_to :capitol
    
    validates :continut, presence: true
    validates :capitol_id, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base

	validates :nume,  presence: true, length: { maximum: 50 }
    validates :prenume,  presence: true, length: { maximum: 50 }
    VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
	validates :email, presence: true, format: { with: VALID_EMAIL_REGEX }, uniqueness: true

	scope :profesori_eligibili, where(rol: "Profesor").where(este_eligibil_licenta: true)
    

end

app/controllers/comentariu_fisiers_controller.rb
class ComentariuFisiersController < ApplicationController
  before_filter :login_required
  before_action :set_comentariu_fisier, only: [:show, :edit, :update, :destroy]

  # GET /comentariu_fisiers
  # GET /comentariu_fisiers.json
  def index
    @comentariu_fisiers = ComentariuFisier.all
  end

  # GET /comentariu_fisiers/1
  # GET /comentariu_fisiers/1.json
  def show
  end

  # GET /comentariu_fisiers/new
  def new
    @comentariu_fisier = ComentariuFisier.new
  end

  # GET /comentariu_fisiers/1/edit
  def edit
  end

  # POST /comentariu_fisiers
  # POST /comentariu_fisiers.json
  def create
    @comentariu_fisier = ComentariuFisier.new(comentariu_fisier_params)

    respond_to do |format|
      if @comentariu_fisier.save
        format.html { redirect_to @comentariu_fisier, notice: 'Comentariu fisier was successfully created.' }
        format.json { render action: 'show', status: :created, location: @comentariu_fisier }
      else
        format.html { render action: 'new' }
        format.json { render json: @comentariu_fisier.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /comentariu_fisiers/1
  # PATCH/PUT /comentariu_fisiers/1.json
  def update
    respond_to do |format|
      if @comentariu_fisier.update(comentariu_fisier_params)
        format.html { redirect_to @comentariu_fisier, notice: 'Comentariu fisier was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @comentariu_fisier.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comentariu_fisiers/1
  # DELETE /comentariu_fisiers/1.json
  def destroy
    @comentariu_fisier.destroy
    respond_to do |format|
      format.html { redirect_to comentariu_fisiers_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comentariu_fisier
      @comentariu_fisier = ComentariuFisier.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def comentariu_fisier_params
      params.require(:comentariu_fisier).permit(:user_id, :fisier_id, :continut)
    end
end

app/helpers/capitols_helper.rb
module CapitolsHelper
end

app/helpers/comentariu_fisiers_helper.rb
module ComentariuFisiersHelper
end

app/helpers/deadlines_helper.rb
module DeadlinesHelper
end

app/helpers/domenius_helper.rb
module DomeniusHelper
end

app/helpers/fisiers_helper.rb
module FisiersHelper
end

app/helpers/licentas_helper.rb
module LicentasHelper
end

app/helpers/sesiunes_helper.rb
module SesiunesHelper
end

app/helpers/temas_helper.rb
module TemasHelper
end

app/helpers/todos_helper.rb
module TodosHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comentariu_fisiers/_form.html.erb
<!-- <= form_for(@comentariu_fisier) do |f| %> -->
  <!-- < if @comentariu_fisier.errors.any? %> -->
    <!-- <div id="error_explanation"> -->
      <!-- <h2><= pluralize(@comentariu_fisier.errors.count, "error") %> prohibited this comentariu_fisier from being saved:</h2> -->

      <!-- <ul> -->
      <!-- < @comentariu_fisier.errors.full_messages.each do |msg| %> -->
        <!-- <li><= msg %></li> -->
      <!-- < end %> -->
      <!-- </ul> -->
    <!-- </div> -->
  <!-- < end %> -->

  <!-- <div class="field"> -->
    <!-- <= f.label :user_id %><br> -->
    <!-- <= f.number_field :user_id %> -->
  <!-- </div> -->
  <!-- <div class="field"> -->
    <!-- <= f.label :fisier_id %><br> -->
    <!-- <= f.number_field :fisier_id %> -->
  <!-- </div> -->
  <!-- <div class="field"> -->
    <!-- <= f.label :continut %><br> -->
    <!-- <= f.text_area :continut %> -->
  <!-- </div> -->
  <!-- <div class="actions"> -->
    <!-- <= f.submit %> -->
  <!-- </div> -->
<!-- < end %> -->

app/views/comentariu_fisiers/edit.html.erb
<!-- <h1>Editing comentariu_fisier</h1>

<= render 'form' %>

<= link_to 'Show', @comentariu_fisier %> |
<= link_to 'Back', comentariu_fisiers_path %>
 -->

app/views/comentariu_fisiers/index.html.erb
<!-- <h1>Listing comentariu_fisiers</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Fisier</th>
      <th>Continut</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    < @comentariu_fisiers.each do |comentariu_fisier| %>
      <tr>
        <td><= comentariu_fisier.user_id %></td>
        <td><= comentariu_fisier.fisier_id %></td>
        <td><= comentariu_fisier.continut %></td>
        <td><= link_to 'Show', comentariu_fisier %></td>
        <td><= link_to 'Edit', edit_comentariu_fisier_path(comentariu_fisier) %></td>
        <td><= link_to 'Destroy', comentariu_fisier, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    < end %>
  </tbody>
</table>

<br>

<= link_to 'New Comentariu fisier', new_comentariu_fisier_path %>
 -->

app/views/comentariu_fisiers/new.html.erb
<!-- <h1>New comentariu_fisier</h1>

<= render 'form' %>

<= link_to 'Back', comentariu_fisiers_path %>
 -->

app/views/comentariu_fisiers/show.html.erb
<!-- <p id="notice"><= notice %></p>

<p>
  <strong>User:</strong>
  <= @comentariu_fisier.user_id %>
</p>

<p>
  <strong>Fisier:</strong>
  <= @comentariu_fisier.fisier_id %>
</p>

<p>
  <strong>Continut:</strong>
  <= @comentariu_fisier.continut %>
</p>

<= link_to 'Edit', edit_comentariu_fisier_path(@comentariu_fisier) %> |
<= link_to 'Back', comentariu_fisiers_path %>
 -->