config/routes.rb
V1FmiLicenta::Application.routes.draw do
  
  resources :deadlines
  resources :comentariu_temas
  resources :comentariu_fisiers
  resources :comentariu_capitols
  resources :comentariu_licentas
  resources :licenta_salvatas
  resources :licentas
  resources :todos
  resources :fisiers
  resources :capitols
  resources :alegeri_user_temas
  resources :temas
  resources :domenius
  resources :users
  resources :sesiunes

  get "browse_pagini/viewDataBase" => "browse_pagini#viewDataBase", as: "viewDataBase"
  get "browse_pagini/listaFeatures" => "browse_pagini#listaFeatures", as: "listaFeatures"
  get "browse_pagini/neutralPage" => "browse_pagini#neutralPage", as: "neutralPage"
  
  get "admin_pagini/controlPanel" => "admin_pagini#controlPanel", as: "controlPanel"
  get "admin_pagini/userSpecializari" => "admin_pagini#userSpecializari", as: "userSpecializari"
  get "browse_pagini/browseHome" => "browse_pagini#browseHome", as: "browseHome"
  get "browse_pagini/browseHomeArhiva" => "browse_pagini#browseHomeArhiva", as: "browseHomeArhiva"
  get "browse_pagini/alegerileMele" => "browse_pagini#alegerileMele", as: "alegerileMele"
  get "browse_pagini/studentiiMei" => "browse_pagini#studentiiMei", as: "studentiiMei"
  get "browse_pagini/temeleMele" => "browse_pagini#temeleMele", as: "temeleMele"
  get "browse_pagini/arhivaHome" => "browse_pagini#arhivaHome", as: "arhivaHome"
  get "browse_pagini/intreabaPage" => "browse_pagini#intreabaPage", as: "intreaba"
  get "licenta_pagini/licentaHome" => "licenta_pagini#licentaHome", as: "licentaHome"

  get "domenius/new" => "domenius#new", as: "domeniuNew"
  get "temas/new" => "temas#new", as: "temaNew"
  get "fisiers/:id/download" => "fisiers#download", as: "download_fisier"

  match "/acceptaCaLicenta" => "browse_pagini#acceptaCaLicenta", :as => :acceptaCaLicenta , via: [:get, :post] # pt a accepta licenta (partea de browse)
  match "/acceptStudenti" => "browse_pagini#acceptStudenti", :as => :acceptStudenti , via: [:get, :post]
  match "/refuzStudenti" => "browse_pagini#refuzStudenti", :as => :refuzStudenti , via: [:get, :post]
  match "/renunta" => "licenta_pagini#renuntaLaLicenta", :as => :renunta , via: [:get, :post]
  match "/submitLicentaFinala" => "licenta_pagini#submitLicentaFinala", :as => :submitLicentaFinala , via: [:get, :post]
  match "intreaba/send", to: "browse_pagini#sendmail", via: "post"
  match "licentaHome/adauga_comentariu", to: "licenta_pagini#adauga_comentariu", via: "post"
  match "fisiers/adauga_comentariu", to: "fisiers#adauga_comentariu", via: "post"
  match "capitols/adauga_comentariu", to: "capitols#adauga_comentariu", via: "post"
  match "intreaba/adauga_comentariu", to: "browse_pagini#adauga_comentariu", via: "post"

  # omniauth
  get '/auth/:provider/callback', :to => 'user_sessions#create'
  get '/auth/failure', :to => 'user_sessions#failure'
  match '/logout', :to => 'user_sessions#destroy', :as => :logout, via: [:get, :post]

  root to: "browse_pagini#neutralPage"

end

app/controllers/licenta_pagini_controller.rb
class LicentaPaginiController < ApplicationController
  before_filter :check_if_owner_or_prof_of_owner
    
  def licentaHome
    # dc e prof tre sa dea prin parametru id-ul studentului
    if(params[:student_id])
      @licenta = Licenta.where(user_id: params[:student_id]).where(renuntat: false).first
      @capitole = @licenta.capitols
      @comentarii = ComentariuLicenta.where(licenta_id: @licenta.id)
      @student_id = params[:student_id]
    # dc e studentul
    else
      @licenta = Licenta.where(user_id: get_current_user.id).where(renuntat: false).first
      @capitole = @licenta.capitols
      @comentarii = ComentariuLicenta.where(licenta_id: @licenta.id)
    end
    
    @progres = 0
    
    if params[:capitol_id] and params[:numar_nou] and params[:numar_victima] and params[:capitol_victima_id] and params[:capitol_id] != "" and params[:numar_nou] != "" and params[:numar_victima] != "" and params[:capitol_victima_id] != ""
      Capitol.find(params[:capitol_id]).update_attributes(numar: params[:numar_nou])
      Capitol.find(params[:capitol_victima_id]).update_attributes(numar: params[:numar_victima])
    end

    # cate todo gata / nr de todos
    # toate todourile din licenta asta
    @todos = Todo.find_by_sql("select * from todos where capitol_id in (select id from capitols where licenta_id=" + @licenta.id.to_s + ")")
    @gata = @todos.select{|t| t.este_gata == true}
    @nugata = @todos.select{|t| t.este_gata == false}
    if @todos.count == 0
      @progres = 0
    else
      @progres = (@gata.count * 100) / @todos.count
    end
  end
  
  def adauga_comentariu
    ComentariuLicenta.create(continut: params[:comentariu], user_id: get_current_user.id, licenta_id: params[:licenta])
    # dc prof
    if(params[:student_id])
      redirect_to licentaHome_path(student_id: params[:student_id])
      else # dc stuedntul
      redirect_to licentaHome_path
    end
  end

  def renuntaLaLicenta
    # gasesc licenta mea - a studentului - ca doar eu pot sa renunt la ea - nu va fi logat un prof sau admin sau secretariat
    @licenta = Licenta.where(user_id: get_current_user.id, renuntat: false).first
    if @licenta
      # eliberez tema
      Tema.find(@licenta.tema_id).update_attributes(este_libera: true)
      # ramane in bd cum ca a apartinut mie si acum i-am dat drumul - in caz ca vreau sa ma intorc la ea
      @licenta.update_attributes(renuntat: true)
    end
    # hai sa imi aleg alta tema
    redirect_to root_path
  end

  def submitLicentaFinala
    # create capitolul de Licenta Finala daca nu exista deja
    if Capitol.where(licenta_id: params[:licenta_id]).where(este_licenta_finala: true).count == 0
      numar = Capitol.where(licenta_id: params[:licenta_id]).count + 1
      capitol = Capitol.create(nume: "Licenta finala", licenta_id: params[:licenta_id], este_licenta_finala: true, numar: numar)
    else
      capitol = Capitol.where(licenta_id: params[:licenta_id]).where(este_licenta_finala: true).first
    end
    redirect_to new_fisier_path(capitol_id: capitol.id)
  end


  protected
  
  def check_if_owner_or_prof_of_owner
    # dc prof - vezi sa fie cel coordonator (vezi in alegeri si statusuri)
    if get_current_user
      if get_current_user.rol == "Student" or get_current_user.rol == "Profesor"
        if(params[:student_id])
            licenta = Licenta.where(user_id: params[:student_id]).first
            temaid = AlegeriUserTema.where(user_id: params[:student_id]).first.tema_id
            tema = Tema.find(temaid)
            if get_current_user.id != Domeniu.find(tema.domeniu_id).user_id
                redirect_to(root_path, :notice =>"Nu ai voie pe pagina de licenta.")
            end
        # dc student - vezi sa fie cel mentionat in licenta
        else
            licenta = Licenta.where(user_id: get_current_user.id).first
            if licenta.user_id != get_current_user.id
                redirect_to(root_path, :notice =>"Nu ai voie pe pagina de licenta.")
            end
        end
      else
        redirect_to root_path
      end # end of if rol
    else
      redirect_to root_path
    end # end of if get_current_user
  end
  
end

app/helpers/licenta_pagini_helper.rb
module LicentaPaginiHelper
end

app/views/licenta_pagini/adauga_comentariu.html.erb
<%= @text %>

app/views/licenta_pagini/licentaHome.html.erb
<% if get_current_user.rol == "Profesor"%>
	<%= User.find(params[:student_id]).nume + " " + User.find(params[:student_id]).prenume + " - " + User.find(params[:student_id]).grupa.to_s %>
	<ol class="breadcrumb">
		<li>Licență Home</li>	
	</ol>
<% end %>

<% tema = Tema.find(@licenta.tema_id) %>
<h1><%= tema.nume%></h1>
<br/><br/>

<!-- notificari -->
<!-- < if flash[:notice] %> -->
   <!-- <div id="notice"><= flash[:notice] %></div> -->
   <!-- <hr> -->
<!-- < end %> -->

<div class="progress">
	<div class="progress-bar progress-bar-success" role="progressbar" aria-valuenow="60" aria-valuemin="0" aria-valuemax="100" style="width: <%= @progres %>%;"><span style="color:black"><%= @progres %>%</span></div>
</div>

<div class="container">
	<div class="row row-offcanvas-right">

		<!-- capitole si todos -->
		<div class="col-sm-8">	
			
			<% if get_current_user.rol == "Profesor" %>
				<div class="well well-sm">
					<span style="font-size:16px; position:relative; left:5px"><b><%= link_to "Fișierele lucrării", fisiers_path(student_id: params[:student_id]) %></b></span>
				</div>
			<% end %>

			<!-- <if @capitole.count == 0%> -->
				<!-- Nu sunt capitole. -->
			<!-- <else%> -->

			<table class="table table-striped table hover">
				<thead>
				<tr>
					<th class="col-sm-1">Nr.</th>
					<% if get_current_user.rol == "Student" %>
						<th class="col-sm-9">Titlu Capitol</th>
						<th class="col-sm-1">Mutare</th>
					<% elsif get_current_user.rol == "Profesor" %>
						<th>Titlu Capitol</th>
					<% end %>
				</tr>
				</thead>
				<tbody>
					<!-- Capitolele -->
					<% @capitole.order(:numar).each do |capitol| %>
						<tr>
							<td>Cap <%= capitol.numar %>.</td>
							<td>
								<% if capitol.este_licenta_finala == true %>
									<%= link_to capitol.nume, capitol, style: "color: green" %>
								<% else %>
									<%= link_to capitol.nume, capitol %>
								<% end %>
							</td>
							<% if get_current_user.rol == "Student" %>
							<td>
								<% if capitol.numar > 1 %>
									<%= link_to "", licentaHome_path(capitol_id: capitol.id, numar_nou: (capitol.numar-1), numar_victima: capitol.numar, capitol_victima_id: @capitole.find_by_numar(capitol.numar-1)), class: "glyphicon glyphicon-arrow-up" %>
								<% end %>
								<% if capitol.numar < @capitole.count %>
									<%= link_to "", licentaHome_path(capitol_id: capitol.id, numar_nou: (capitol.numar+1), numar_victima: capitol.numar, capitol_victima_id: @capitole.find_by_numar(capitol.numar+1)), class: "glyphicon glyphicon-arrow-down" %>
								<% end %>
							</td>
							<% end %>
						</tr>

						<!-- ToDo-urile -->
						<tr>
							<td></td>
							<td>
								<% if Todo.where(capitol_id: capitol.id).count > 0 %>
								<ul class="list-group">
								<% Todo.where(capitol_id: capitol.id).each do |todo| %>
										<%if get_current_user.rol == "Student"%>
											<% if todo.este_gata == true %>
												<li class="list-group-item list-group-item-success"><%= link_to "DONE: " + todo.continut, edit_todo_path(todo, capitol_id: capitol.id), {:style => "color:green"} %></li>
											<% elsif todo.este_gata == false %>
												<li class="list-group-item list-group-item-danger"><%= link_to "TODO: " + todo.continut, edit_todo_path(todo, capitol_id: capitol.id), {:style => "color:red"} %></li>
											<% end %>
											
										<%elsif get_current_user.rol == "Profesor" %>
											<% if todo.este_gata == true %>
												<li class="list-group-item list-group-item-success"><%= "DONE: " + todo.continut %></li>
											<% elsif todo.este_gata == false %>
												<li class="list-group-item list-group-item-danger"><%= "TODO: " + todo.continut %></li>
											<% end %>
											
										<%end%>
								<%end%>
								</ul>
								<% end %> <!-- end if todos count > 0-->
							</td>
							<% if get_current_user.rol == "Student" %>
							<td></td>
							<% end %>
						</tr>
					<% end %> <!-- end of capitole...each -->	

					<% if get_current_user.rol == "Student" %>
						<tr>
							<td></td>
							<td>
								<!-- Daca user-ul curent logat este si cel care va lucra la aceasta licenta, avem si link pt a adauga un nou capitol--> 
								<% if get_current_user.id == @licenta.user_id %> 
									<%= link_to '+ Adauga capitol', new_capitol_path(:licenta => @licenta.id) %>
								<% end %>
							</td>
							<td></td>
						</tr>
					<% end %>
				</tbody>
			</table>

			<br/>
			<% if get_current_user.rol == "Student" %>
				<%= link_to "Submit licenta finala", submitLicentaFinala_path(licenta_id: @licenta.id), class: "btn btn-success" %>
			<% end %>
			<!-- <end%> -->
		</div>


		<!-- comentarii pe dreapta -->
		<div class="col-sm-3 sidebar-offcanvas" style="overflow:auto; height: 550px">
			<%if @comentarii.count == 0%>
				<em>Nu sunt comentarii.</em>
				<br/><br/>
			<%else%>
				<%@comentarii.each do |comentariu|%>
					<% if User.find(comentariu.user_id).rol == "Profesor" %>
						<div class="panel panel-default">
						  <div class="panel-heading">
						    	<b><%= User.find(comentariu.user_id).nume + " " + User.find(comentariu.user_id).prenume%> : </b><br/> 
								<em><%= comentariu.created_at.strftime("%d %b. %Y,  %H:%M") %></em>
						  </div>
						  <div class="panel-body">
						    <%= comentariu.continut %>
						  </div>
						</div>
						
					<% else %>
						<div class="panel panel-info">
						  <div class="panel-heading">
						    	<b><%= User.find(comentariu.user_id).nume + " " + User.find(comentariu.user_id).prenume%> : </b><br/> 
								<em><%= comentariu.created_at.strftime("%d %b. %Y,  %H:%M") %></em>
						  </div>
						  <div class="panel-body">
						    <%= comentariu.continut %>
						  </div>
						</div>
						
					<% end %>
				<%end%>
			<%end%>
				
			<%= form_tag(licentaHome_adauga_comentariu_path(:student_id => @student_id), method: "post") do%>
					<%= hidden_field_tag(:licenta, @licenta.id , class: "form-control") %>
				<div class="field">
					<%= text_area_tag(:comentariu, nil , :required => true, class: "form-control",rows:5) %>
				</div>
				<br/>
				<%= submit_tag "Adaugă comentariu", class: "btn btn-primary" %>
			<%end%>

			<% if get_current_user.rol == "Student" %>
				<br/>
				<%= link_to "Renunta la licenta asta", renunta_path, data: {confirm: "Sigur renunti la licenta asta? O data luata de altcineva toata munca va fi pierduta."} %>
			<% end %>

		</div>

	</div>
</div>